### ISSUE TITLE
[BUG]: Sometimes redirected to robots.txt

### ISSUE THREAD

**Issue by ImBIOS** [logtail/logtail-js#28] opened 2022-12-20 03:25 UTC
![image](https://user-images.githubusercontent.com/41441643/208574594-29178b22-cd84-42ec-91a1-743a0be37cfb.png)

Still didn't know how to reproduce.

**Comment by adikus** [comment] 2022-12-20 09:21
@ImBIOS Thanks for the report! 
Can you provide some more context?
What URLs have redirected you to /robots.txt?
How is this related to the logtail-js library?

**Comment by curusarn** [comment] 2023-02-22 13:43
I am closing this issue because we can't reproduce it.

Please feel free to reopen it if you have more information or questions.
You can always message us at [hello@betterstack.com](mailto:hello@betterstack.com). We're happy to help. 🙏

**Closed by curusarn** 2023-02-22 13:43 UTC
