### ISSUE TITLE
Add cycle detection in Node sanitization for encoding

### ISSUE THREAD

**Issue by yagotome** [logtail/logtail-js#19] opened 2022-09-01 16:39 UTC
Hello!

I'm using Logtail and just noticed an error on trying to log some metadata based on objects in my app that have circular references. This is the stack trace:

```log
RangeError: Maximum call stack size exceeded
    at /my_app/node_modules/@logtail/node/src/node.ts:104:37
    at Array.forEach (<anonymous>)
    at Node.sanitizeForEncoding (/my_app/node_modules/@logtail/node/src/node.ts:104:29)
    at /my_app/node_modules/@logtail/node/src/node.ts:108:29
    at Array.forEach (<anonymous>)
    at Node.sanitizeForEncoding (/my_app/node_modules/@logtail/node/src/node.ts:104:29)
    at /my_app/node_modules/@logtail/node/src/node.ts:108:29
    at Array.forEach (<anonymous>)
    at Node.sanitizeForEncoding (/my_app/node_modules/@logtail/node/src/node.ts:104:29)
    at /my_app/node_modules/@logtail/node/src/node.ts:100:39
```

That links to this piece of code, which is ignoring possible reference cycles:

https://github.com/logtail/logtail-js/blob/174eee03ca3baebbddbad0cb17da23c11ea0fb93/packages/node/src/node.ts#L104-L112

So, if I may share my opinion, I believe cycles coming from the context object should be cut off by not propagating them after sanitization operation.

**Comment by boly38** [comment] 2022-12-21 16:23
I'just say that I'm able to reproduce this issue with `@logtail/node@0.1.14` and this is not fixed in logtail librairy side.

I'll come back with an HowToReproduce right here but (my context) this seems to be when using a mongo object as context object argument. Mongo object include circular references. The fix would be to use mongo `lean()` method for a find query for example to get a plain old json object without circular ref.

**Comment by boly38** [comment] 2022-12-21 17:42
@gyfis please reopen this issue to avoid duplicate.

I isolate this use case in a dedicated [test sample](https://github.com/boly38/logtailSample/blob/main/tests/logtailNode_MaxStackIssue.js), cf. [logtailSample readme](https://github.com/boly38/logtailSample#circular-reference-use-case)

**Closed** 2023-01-10 10:40 UTC
